//
// Created by chenjs on 2019/10/22.
//

#ifndef TINYJ_INSTRUCTION_H
#define TINYJ_INSTRUCTION_H

#include "Primitive.h"

namespace TinyJ{

enum class OpCode: U8{
    //LOAD AND STORE
    //LOAD
    I_LOAD, I_LOAD_0, I_LOAD_1, I_LOAD_2, I_LOAD_3,
    L_LOAD, L_LOAD_0, L_LOAD_1, L_LOAD_2, L_LOAD_3,
    F_LOAD, F_LOAD_0, F_LOAD_1, F_LOAD_2, F_LOAD_3,
    D_LOAD, D_LOAD_0, D_LOAD_1, D_LOAD_2, D_LOAD_3,
    A_LOAD, A_LOAD_0, A_LOAD_1, A_LOAD_2, A_LOAD_3,
    //STORE
    I_STORE, I_STORE_0, I_STORE_1, I_STORE_2, I_STORE_3,
    L_STORE, L_STORE_0, L_STORE_1, L_STORE_2, L_STORE_3,
    F_STORE, F_STORE_0, F_STORE_1, F_STORE_2, F_STORE_3,
    D_STORE, D_STORE_0, D_STORE_1, D_STORE_2, D_STORE_3,
    A_STORE, A_STORE_0, A_STORE_1, A_STORE_2, A_STORE_3,
    //PUSH
    BI_PUSH, SI_PUSH, LDC, LDC_W, LDC2_W,
    A_CONST_NULL,
    I_CONST_M1,
    I_CONST_0 ,
    I_CONST_1,
    I_CONST_2,
    I_CONST_3,
    I_CONST_4,
    I_CONST_5,
    L_CONST_0,
    L_CONST_1,
    F_CONST_0,
    F_CONST_1,
    F_CONST_2,
    D_CONST_0,
    D_CONST_1,
    WIDE,
    //OP
    I_ADD, L_ADD, F_ADD, D_ADD,
    I_SUB, L_SUB, F_SUB, D_SUB,
    I_MUL, L_MUL, F_MUL, D_MUL,
    I_DIV, L_DIV, F_DIV, D_DIV,
    I_REM, L_REM, F_REM, D_REM,
    I_NEG, L_NEG, F_NEG, D_NEG,
    I_SHL, I_SHR, I_U_SHR, L_SHL, L_SHR, L_U_SHR,
    I_OR, L_OR,
    I_AND, L_AND,
    I_XOR, L_XOR,
    I_INC,
    D_CMP_G, D_CMP_L, F_CMP_G, F_CMP_L,L_CMP,
    //CAST
    I2L, I2F, I2D,
    L2F, L2D,
    F2D,
    I2B, I2C, I2S,
    L2I,
    F2I, F2L,
    D2I, D2L, D2F,
    //OBJECT
    NEW, NEW_ARRAY, A_NEW_ARRAY, MULTI_A_NEW_ARRAY,
    GET_FIELD, PUT_FIELD, GET_STATIC, PUT_STATIC,
    B_A_LOAD, C_A_LOAD, S_A_LOAD, I_A_LOAD, L_A_LOAD, F_A_LOAD, D_A_LOAD, A_A_LOAD,
    B_A_STORE, C_A_STORE, S_A_STORE, I_A_STORE, L_A_STORE, F_A_STORE, D_A_STORE, A_A_STORE,
    ARRAY_LENGTH,
    INSTANCE_OF, CHECK_CAST,
    //STACK
    POP, POP2, DUP, DUP2, DUP_X1, DUP_X2, DUP2_X1, DUP2_X2, SWAP,
    //CONTROL FLOW
    //COND
    IF_EQ, IF_NE, IF_LT, IF_LE, IF_GT, IF_GE, IF_NULL, IF_NON_NULL,
    IF_I_CMP_EQ, IF_I_CMP_NE, IF_I_CMP_LT, IF_I_CMP_LE, IF_I_CMP_GT, IF_I_CMP_GE,
    IF_A_CMP_EQ, IF_A_CMP_NE,
    //SWITCH
    TABLE_SWITCH, LOOKUP_SWITCH,
    //JUMP
    GOTO, GOTO_W, JSR, JSR_W, RET, RET_W,
    //CALL RETURN
    //CALL
    INVOKE_VIRTUAL, INVOKE_INTERFACE, INVOKE_SPECIAL, INVOKE_STATIC, INVOKE_DYNAMIC,
    //RETURN
    I_RETURN, L_RETURN, F_RETURN, D_RETURN, A_RETURN, V_RETURN,
    //EXCEPTION
    A_THROW,
    //SYNCHRONIZED
    MONITOR_ENTER, MONITOR_EXIT,
};

}

#endif //TINYJ_INSTRUCTION_H
